### ISSUE TITLE
What's the project?

### ISSUE THREAD

**Issue by hs115488** [kelbahloul/Python-Data-Analysis-Projects-#1]

**Comment by kelbahloul** [comment]
This project I will be analyzing the stock ticker LLY as well as using time series forecasting to predict its closing price. Now, it’s great to predict but as everyone knows the market is unpredictable so anything can happen, but overall this is just an analysis with details to explain their significance. 
Overall, this is a great project and I will continue to do more of the same with other ticker symbols

**Comment by hs115488** [comment]
So what's the project?
